# node-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-executor
  template:
    metadata:
      labels:
        app: node-executor
    spec:
      containers:
      - name: node
        image: node-image
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"