apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 8000  # port on which service is exposed to internal systemp within the cluster  # entry point for the traffic for the service
      targetPort: 8000    # service will forward its traffic from port to the target port which is application running port :8000
      nodePort: 30000   # service will recieve the traffic on nodePort 