# python-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-executor
  template:
    metadata:
      labels:
        app: python-executor
    spec:
      containers:
      - name: python
        image: python-image
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"