# cpp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-executor
  template:
    metadata:
      labels:
        app: cpp-executor
    spec:
      containers:
      - name: cpp
        image: cpp-image
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"